# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'FinalRetake' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FinalRetake

pod 'Firebase/Auth'
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Storage'
pod 'Kingfisher'

  target 'FinalRetakeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
